image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - package
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: openplatform/chain


###########################
# Tests
###########################
unit-tests:
  stage: test
  image: openjdk:8-jdk
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew check
  after_script:
    - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    when: always
    paths:
      - build/reports/
    expire_in: 1 day


###########################
# Building
###########################
build-jar:
  stage: build
  image: openjdk:8-jdk
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew assemble
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 day
  only:
    - sprint
    - master
    - tags

###########################
# Packaging
###########################
package-docker:
  stage: package
  script:
    - if [[ ${CI_COMMIT_REF_NAME} == master ]]; then export IMAGE_TAG=latest; else export IMAGE_TAG=${CI_COMMIT_REF_NAME}; fi;
    - docker login -u ${DOCKER_LOGIN} -p ${DOCKER_PASS}
    - docker build -t ${IMAGE_NAME}:${IMAGE_TAG} .
    - docker push ${IMAGE_NAME}:${IMAGE_TAG}
  only:
    - sprint
    - master
    - tags

package-native:
  stage: package
  script:
    - mv build/libs/open-chain-*.jar build/libs/open-chain.jar
    - |
      docker run --rm -v "$(pwd):/packages" openplatform/install4j:full \
            /JRE/install4j7.0.6/bin/install4jc --license=${INSTALL4J_KEY} \
            /packages/install4j/multi.install4j
  artifacts:
    paths:
      - artifacts/*
    expire_in: 1 day
  only:
    - tags


###########################
# Deploy
###########################
deploy-production:
  stage: deploy
  image: openplatform/ansible
  script:
    - echo "${DEPLOY_KEY_PROD}" | tr -d '\r' > ansible/key.pem
    - chmod 600 ansible/key.pem
    - export ANSIBLE_HOST_KEY_CHECKING=False
    - ansible-playbook --private-key=ansible/key.pem -i ansible/inventory -e "image_tag=${CI_COMMIT_REF_NAME}" -e "count=1" -e "user_login=${DEPLOY_USER_PROD}" ansible/deploy.yml
  only:
    - tags