image: docker:latest

services:
  - docker:dind

stages:
  - test
  - build
  - package
  - deploy

variables:
    DOCKER_DRIVER: overlay2


###########################
# Building
###########################
unit-tests:
  stage: test
  image: openjdk:8-jdk
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew check
  after_script:
    - cat build/reports/jacoco/test/html/index.html
  coverage: '/Total.*?([0-9]{1,3})%/'
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    when: always
    paths:
      - build/reports/
    expire_in: 1 week
  except:
    - schedules


build-jar:
  stage: build
  image: openjdk:8-jdk
  before_script:
    - export GRADLE_USER_HOME=`pwd`/.gradle
  script:
    - ./gradlew assemble
  cache:
    paths:
      - .gradle/wrapper
      - .gradle/caches
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week
  only:
    - master
    - sprint
  except:
    - schedules