apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: production-openchain
  labels:
    #Project ID
    app: chain
  namespace: openchain-app
spec:
  #Run two instances of our application
  replicas: 2
  template:
    metadata:
      labels:
        app: chain
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: app
                operator: In
                values:
                - chain
            topologyKey: kubernetes.io/hostname
      #Container details
      containers:
        - name: openchain
          image: openplatform/chain:IMAGE_TAG
          imagePullPolicy: Always
          #Ports to expose
          ports:
          - containerPort: 9190
          - containerPort: 8080

---

kind: Service
apiVersion: v1
metadata:
  name: chain-service
  namespace: openchain-app
spec:
  selector:
    app: chain
  type: LoadBalancer
  loadBalancerIP: LB_IP
  ports:
  - name: tcp
    protocol: TCP
    port: 9190
    targetPort: 9190
  - name: http
    protocol: TCP
    port: 8080
    targetPort: 8080
