---
- hosts: all
  remote_user: "{{ user_login }}"
  serial: "{{ count }}"
  gather_facts: False
  tasks:
    - name: Re-create openchain container
      docker_container:
        name: openchain-test-{{ item.app_port }}
        image: openplatform/chain:{{ image_tag }}
        state: started
        env:
          RPC_PORT: "{{ item.app_port }}"
          NODE_PORT: "{{ item.api_port }}"
          KEY: { "externalPort" : "{{ item.api_port }}", "externalHost" : "", "secret" : "{{ item.secret_key }}" }
        restart_policy: always
      with_items:
        - { app_port: '9090', api_port: '9190', secret_key: '{{ key1 }}' }
        - { app_port: '9091', api_port: '9191', secret_key: '{{ key2 }}' }
    - name: Delete old images
      shell: docker image prune -a --force --filter "until=24h"
