---
- hosts: all
  remote_user: "{{ user_login }}"
  serial: "{{ count }}"
  gather_facts: False
  tasks:
    - name: Remove openchain container
      docker_container:
        name: openchain
        state: absent
    - name: Re-create openchain container
      docker_container:
        name: openchain
        image: openplatform/chain:{{ image_tag }}
        state: started
        pull: yes
        env:
          RPC_PORT: "{{ item.app_port }}"
          NODE_PORT: "{{ item.api_port }}"
          KEY: '{ "externalPort" : {{ item.api_port }}, "externalHost" : "", "secret" : "{{ item.secret_key }}" }'
          JMX_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=8000 -Dcom.sun.management.jmxremote.rmi.port=7000 -Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.port=7000 -Dcom.sun.management.jmxremote.ssl=false -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.local.only=false -Djava.rmi.server.hostname={{ansible_host}}"
        published_ports:
          - "{{ item.app_port }}:{{ item.app_port }}"
          - "{{ item.api_port }}:{{ item.api_port }}"
          - 7000:7000
          - 8000:8000
        restart_policy: always
      with_items:
        - { app_port: 9090, api_port: 9190, secret_key: "{{ key }}" }
      no_log: True
    - name: Delete old images
      shell: docker image prune -a --force --filter "until=24h"
