---
- hosts: all
  remote_user: "{{ user_login }}"
  serial: "{{ count }}"
  gather_facts: False
  tasks:
    - name: Remove openchain container
      docker_container:
        name: openchain
        state: absent
    - name: Re-create openchain container
      docker_container:
        name: openchain
        image: openplatform/chain:{{ image_tag }}
        state: started
        pull: yes
        env:
          RPC_PORT: "{{ item.app_port }}"
          NODE_PORT: "{{ item.api_port }}"
          KEY: '{ "externalPort" : {{ item.api_port }}, "externalHost" : "", "secret" : "{{ item.secret_key }}" }'
        published_ports:
          - "{{ item.app_port }}:{{ item.app_port }}"
          - "{{ item.api_port }}:{{ item.api_port }}"
        restart_policy: always
      with_items:
        - { app_port: 9090, api_port: 9190, secret_key: "{{ key }}" }
      no_log: True
    - name: Delete old images
      shell: docker image prune -a --force --filter "until=24h"
