---
- hosts: all
  remote_user: "{{ user_login }}"
  serial: "{{ count }}"
  gather_facts: False
  tasks:
    - name: Re-create openchain container
      docker_container:
        name: openchain
        image: openplatform/chain:{{ image_tag }}
        state: started
        published_ports:
          - 8080:8080
          - 9190:9190
        restart_policy: always
    - name: Delete old images
      shell: docker image prune -a --force --filter "until=24h"
