---
- hosts: all
  remote_user: "{{ user_login }}"
  serial: "{{ count }}"
  gather_facts: False
  tasks:
    - name: Stop a container
      docker_container:
        name: openchain
        state: stopped
      register: container_info
      ignore_errors: yes
    - name: Delete old image
      docker_image:
        state: absent
        name: "{{ container_info.ansible_facts.docker_container.Config.Image }}"
        force: true
      ignore_errors: yes
    - name: Re-create openchain container
      docker_container:
        name: openchain
        image: openplatform/chain:{{ image_tag }}
        state: started
        published_ports:
          - 8080:8080
          - 9190:9190
        restart_policy: always